[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"

# Future - necessary for the experimental "native build" of esp-idf-sys with ESP32C3
# See also https://github.com/ivmarkov/embuild/issues/16
rustflags = ["-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
# === Native builder ===
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }
# Same thing but for the native build. Currently the native and PIO builds disagree how sdkconfig configuration should be passed to the ESP-IDF build
# See https://github.com/esp-rs/esp-idf-sys/issues/10#issuecomment-919022205
ESP_IDF_SDKCONFIG = { value = "sdkconfig.debug" }
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "./sdkconfig.defaults", relative = true }

# Enables the esp-idf-sys "native" build feature to build against ESP-IDF upcoming (v4.4)
#ESP_IDF_VERSION = { value = "branch:release/v4.4" }
# Enables the esp-idf-sys "native" build feature to build against ESP-IDF master (v5.0)
ESP_IDF_VERSION = { value = "master" }
